# Generated by Django 5.1.3 on 2025-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='zarezerwowane',
            field=models.BooleanField(default=False),
        ),
    ]
